# Generated by Django 5.1 on 2024-12-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                ("email", models.EmailField(max_length=254, verbose_name="e-mail")),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="telefone"
                    ),
                ),
                ("message", models.CharField(max_length=200, verbose_name="mensagem")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="recebido em"),
                ),
                (
                    "response_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="respondido em"
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="resposta"
                    ),
                ),
            ],
            options={
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
                "ordering": ("-sent_at",),
            },
        ),
    ]
