# Generated by Django 5.1 on 2024-12-16 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "contato",
                "verbose_name_plural": "contatos",
            },
        ),
        migrations.RemoveField(
            model_name="contact",
            name="response_at",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="criado em",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="reply_created_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="respondida em"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="response",
            field=models.TextField(
                blank=True, default="", max_length=200, verbose_name="resposta"
            ),
        ),
    ]
