# Generated by Django 5.1 on 2024-11-26 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_alter_subscription_options_alter_subscription_cpf_and_more",
        ),
        ("subscriptions", "0003_alter_subscription_options_subscription_paid_and_more"),
        ("subscriptions", "0003_alter_subscription_paid"),
        ("subscriptions", "0004_alter_subscription_paid"),
    ]

    operations = []
