# Generated by Django 5.1 on 2024-12-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_merge_20241126_1949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="pago"),
        ),
    ]
